"""modifier le champ boolean

Revision ID: 76357e748d81
Revises: e86814b6bd31
Create Date: 2021-03-28 13:20:39.791636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76357e748d81'
down_revision = 'e86814b6bd31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
