"""ajout taux de change

Revision ID: 876e4db7c26b
Revises: 084fb419d120
Create Date: 2021-04-17 13:23:21.035620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '876e4db7c26b'
down_revision = '084fb419d120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contrats', sa.Column('currency', sa.String(length=3), nullable=True))
    op.add_column('contrats', sa.Column('taux_change', sa.Float(), nullable=True))
    op.add_column('positions', sa.Column('currency', sa.String(length=3), nullable=True))
    op.add_column('positions', sa.Column('gain_can', sa.Float(), nullable=True))
    op.add_column('titres', sa.Column('currency', sa.String(length=3), nullable=True))
    op.add_column('titres', sa.Column('taux_change', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('titres', 'taux_change')
    op.drop_column('titres', 'currency')
    op.drop_column('positions', 'gain_can')
    op.drop_column('positions', 'currency')
    op.drop_column('contrats', 'taux_change')
    op.drop_column('contrats', 'currency')
    # ### end Alembic commands ###
