"""ajout strike et style dans les positions

Revision ID: e86814b6bd31
Revises: df7b8cb1f352
Create Date: 2021-03-28 11:28:45.130919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e86814b6bd31'
down_revision = 'df7b8cb1f352'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('strike', sa.Float(), nullable=True))
    op.add_column('positions', sa.Column('style', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'style')
    op.drop_column('positions', 'strike')
    # ### end Alembic commands ###
